[build-system]
# Minimum requirements for the build system to execute
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm[toml]>=3.4",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target_version = ["py37"]

[tool.flynt]
line-length = 79
verbose = true

[tool.isort]
profile = "black"
src_paths = ["pynhm", "autotest"]
line_length = 79
