name: pynhm-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - netCDF4
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pyyaml
  - xarray
  - pip:
    - black
    - isort
    - flake8
    - pylint
