name: pynhm-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - netCDF4
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pyyaml
  - xarray
  - flopy
  - pip:
      - click>8.1.0,<8.1.0
      - black
      - isort
      - flake8
      - pylint
