name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  #env:
  #WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18417/w_HPCKit_p_2022.1.0.93_offline.exe
  #LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18438/l_HPCKit_p_2022.1.1.97_offline.sh
#  MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18341/m_HPCKit_p_2022.1.0.86_offline.dmg

jobs:
  pynhm_setup:
    name: standard installation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:

      # check out repo
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Upgrade pip and install wheel
        run: |
          pip install wheel

      - name: Base installation
        run: |
          pip install .

      - name: Print pyhmn version
        run: |
          python -c "import pynhm; print(pynhm.__version__)"


  pynhm_lint:
    name: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      # check out repo
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r ./ci/requirements/environment.txt

      - name: Version info
        run: |
          pip -V
          pip list

      - name: Run isort
        run: |
          echo "if isort check fails update isort using"
          echo "  pip install isort --upgrade"
          echo "and run"
          echo "  isort ./pynhm"
          echo "and then commit the changes."
          isort --check --diff ./pynhm

      - name: Run black
        run: |
          echo "if black check fails update black using"
          echo "  pip install black --upgrade"
          echo "and run"
          echo "  black ./pynhm"
          echo "and then commit the changes."
          black --check --diff ./pynhm

      - name: Run flake8
        run: |
          flake8 --count --show-source --exit-zero ./pynhm

      - name: Run pylint
        run: |
          pylint --jobs=2 --errors-only --exit-zero ./pynhm


  test:
    name: ${{ matrix.os}} py${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.8" ]  # , "3.9", "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and this package
        run: |
          pip install wheel
          pip install -r ./ci/requirements/environment.txt
          pip install .

      - name: Version info
        run: |
          pip -V
          pip list

      #- name: Import pynhm
      #  run: |
      #    python -c "import pynhm"

      - name: Run tests
        working-directory: autotest
        run: pytest
          -v
          -n=auto
          --cov=pynhm
          --cov-report=xml
          --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ runner.os }}-${{ matrix.python-version }}
          path: ./autotest/pytest.xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./autotest/coverage.xml
          # flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          # name: codecov-umbrella
          fail_ci_if_error: false
          version: "v0.1.15"
