name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: ${{ matrix.os}} py${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9"]  #, "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        
      - name: Set environment variables
        run: |
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install -r ./ci/requirements/environment.txt
      - name: Version info
        run: |
          pip -V
          pip list

      - name: Install this package
        run: |
          python -m pip install --no-deps -e .

      - name: Import pynhm
        run: |
          python -c "import pynhm"

      - name: Run tests
        run: python -m pytest -n 4
          --cov=pynhm
          --cov-report=xml
          --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ runner.os }}-${{ matrix.python-version }}
          path: pytest.xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./coverage.xml
          # flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          # name: codecov-umbrella
          fail_ci_if_error: false
          version: "v0.1.15"          
