name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

#env:
  #WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18417/w_HPCKit_p_2022.1.0.93_offline.exe
  #LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18438/l_HPCKit_p_2022.1.1.97_offline.sh
#  MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/18341/m_HPCKit_p_2022.1.0.86_offline.dmg

jobs:
  test:
    name: ${{ matrix.os}} py${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["macos-latest"]
        python-version: ["3.8"]  # , "3.9", "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Set environment variables
        run: |
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip3 install -r ./ci/requirements/environment.txt
      - name: Version info
        run: |
          pip3 -V
          pip3 list

      - name: Install this package
        run: |
          python3 -m pip install --no-deps -e .

      #- name: Import pynhm
      #  run: |
      #    python -c "import pynhm"

      - name: Run tests
        working-directory: autotest
        run: python3 -m pytest -n 4
          --cov=pynhm
          --cov-report=xml
          --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ runner.os }}-${{ matrix.python-version }}
          path: pytest.xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./coverage.xml
          # flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          # name: codecov-umbrella
          fail_ci_if_error: false
          version: "v0.1.15"          
